// <auto-generated />
using System;
using EstimaNow.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstimaNow.Infrastructure.Migrations
{
    [DbContext(typeof(EstimaNowDbContext))]
    partial class EstimaNowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstimaNow.Domain.Entities.CategoryOfService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesOfServices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Serviços de manutenção preventiva e corretiva",
                            Name = "Manutenção"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Serviços de consultoria e assessoria",
                            Name = "Consultoria"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Serviços de instalação de equipamentos e sistemas",
                            Name = "Instalação"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Serviços de treinamento e capacitação",
                            Name = "Treinamento"
                        });
                });

            modelBuilder.Entity("EstimaNow.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("EstimaNow.Domain.Entities.OrderOfService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CategoryOfServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FinishedIn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observations")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryOfServiceId");

                    b.HasIndex("ClientId");

                    b.ToTable("OrdersOfSerives");
                });

            modelBuilder.Entity("EstimaNow.Domain.Entities.OrderOfService", b =>
                {
                    b.HasOne("EstimaNow.Domain.Entities.CategoryOfService", "CategoryOfService")
                        .WithMany("Orders")
                        .HasForeignKey("CategoryOfServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstimaNow.Domain.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryOfService");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EstimaNow.Domain.Entities.CategoryOfService", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EstimaNow.Domain.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
